-- =====================================================================
-- USP_UPD_INS_REGISTRO_CLIENTE  (olimpo_reserva)
-- Login del cliente por NUMERO_DOCUMENTO + recuperacion por correo / WhatsApp
--
-- Cambios respecto a la version previa (backup en sql/backup/):
--   OPCION 1  : ubica al cliente por NUMERO_DOCUMENTO (antes EMAIL)
--   OPCION 2  : ubica por NUMERO_DOCUMENTO y devuelve tambien
--               NUMERO_DOCUMENTO / EMAIL / NRO_CELULAR (para detectar 1er ingreso)
--   OPCION 4  : ubica por NUMERO_DOCUMENTO (antes EMAIL)
--   OPCION 10 : corrige columnas NUM_DOCUMENTO -> NUMERO_DOCUMENTO
--                                CLIENTE_MODIFICA -> USUARIO_MODIFICA
--   OPCION 12 : NUEVA - recupera contrasena por celular. Devuelve
--               NUMERO_DOCUMENTO, NRO_CELULAR, EMAIL y NRO_WHATSAPP de la sucursal
--   OPCION 13 : NUEVA - verifica que el celular exista (pre-recuperacion)
-- =====================================================================
DROP PROCEDURE IF EXISTS USP_UPD_INS_REGISTRO_CLIENTE;
DELIMITER $$
CREATE PROCEDURE USP_UPD_INS_REGISTRO_CLIENTE(IN _ID INT, IN _CLIENTE VARCHAR(100), IN _CONTRASENA VARCHAR(255), IN _OPCION INT,
								IN _IP VARCHAR(20), IN _SERVER VARCHAR(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION, SQLWARNING
BEGIN
ROLLBACK;
SHOW ERRORS LIMIT 1;
RESIGNAL;
END;
START TRANSACTION;

	IF _OPCION=1 THEN
		SET @IDCLIENTE=(SELECT ID_CLIENTE FROM MAE_CLIENTE WHERE NUMERO_DOCUMENTO =_CLIENTE LIMIT 1);
		SET @INTENTO=(SELECT INTENTO FROM MAE_CLIENTE WHERE ID_CLIENTE=@IDCLIENTE);
		SET @ESTADO=(SELECT ES_VIGENTE FROM MAE_CLIENTE WHERE ID_CLIENTE=@IDCLIENTE);
		SET @ELIMINA=(SELECT ES_ELIMINADO FROM MAE_CLIENTE WHERE ID_CLIENTE=@IDCLIENTE);
		SET @SESION=(SELECT SESION FROM MAE_CLIENTE WHERE ID_CLIENTE=@IDCLIENTE);

		IF @ELIMINA=1 THEN
			INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
			VALUES (NOW(),@IDCLIENTE,'CLIENTE ELIMINADO',_IP,_SERVER);
			SELECT '¡Sus credenciales no existen en la base de datos, han sido eliminados!' AS MENSAJE, 'EL' as TIPO, '' AS CORREO;
		ELSEIF @ESTADO=0 THEN
			INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
			VALUES (NOW(),@IDCLIENTE,'CLIENTE INACTIVO',_IP,_SERVER);
			SELECT '¡Su sesión esta inactiva, comuniquese con el administrador!' AS MENSAJE, 'ES' AS TIPO, '' AS CORREO;
		ELSEIF @INTENTO>=3 THEN
			SET @CORREO=(SELECT EMAIL FROM MAE_CLIENTE WHERE ID_CLIENTE=@IDCLIENTE);
			INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
			VALUES (NOW(),@IDCLIENTE,'CLIENTE BLOQUEADO',_IP,_SERVER);
			SELECT '¡Su sesión esta bloqueada, por superar el número de intentos permitidos (3)!' AS MENSAJE, 'BL' AS TIPO, @CORREO AS CORREO;
		ELSE
			INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
			VALUES (NOW(),@IDCLIENTE,'ACCESO CORRECTO',_IP,_SERVER);

			SELECT MC.ID_CLIENTE,MS.ID_SUCURSAL,MS.ID_EMPRESA,'0' AS MENSAJE, 'OK' AS TIPO, MC.EMAIL AS CORREO
			FROM MAE_CLIENTE MC
			INNER JOIN MAE_SUCURSAL MS ON MC.ID_SUCURSAL=MS.ID_SUCURSAL
			WHERE MC.ID_CLIENTE=@IDCLIENTE LIMIT 1;
		END IF;
	ELSEIF _OPCION=2 THEN
		SELECT ID_CLIENTE,CONTRASENA,SESION,NUMERO_DOCUMENTO,EMAIL,NRO_CELULAR
		FROM MAE_CLIENTE WHERE NUMERO_DOCUMENTO =_CLIENTE LIMIT 1;
	ELSEIF _OPCION=3 THEN
		UPDATE MAE_CLIENTE
		SET INTENTO=0,
			SESION='A'
		WHERE ID_CLIENTE=_ID;
	ELSEIF _OPCION=4 THEN
		SET @IDCLIENTE=(SELECT ID_CLIENTE FROM MAE_CLIENTE WHERE NUMERO_DOCUMENTO =_CLIENTE LIMIT 1);

		UPDATE MAE_CLIENTE
		SET INTENTO=INTENTO+1
		WHERE ID_CLIENTE=@IDCLIENTE;

		INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
		VALUES (NOW(),@IDCLIENTE,'CONTRASENA INCORRECTA',_IP,_SERVER);

		SELECT EMAIL,INTENTO FROM MAE_CLIENTE WHERE ID_CLIENTE=@IDCLIENTE;
	ELSEIF _OPCION=5 THEN
		SET @IDCLIENTE=(SELECT ID_CLIENTE FROM MAE_CLIENTE WHERE NUMERO_DOCUMENTO =_CLIENTE);
		INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
		VALUES (NOW(),@IDCLIENTE,'CARACATERES NO PERMITIDOS',_IP,_SERVER);
		SELECT '¡Existen caracteres que no estan permitidos, solo puede usar:\nnumeros\n, letras (mayúsculas\n y minúsculas),\n y estos caracteres especiales (@_-.)!' AS MENSAJE;
	ELSEIF _OPCION=6 THEN
		INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
		VALUES (NOW(),_ID,'SESIÓN TERMINADA',_IP,_SERVER);

		UPDATE MAE_CLIENTE
		SET INTENTO=0,
			SESION='I'
		WHERE ID_CLIENTE=_ID;

		SELECT _ID AS IDCLIENTE;
	ELSEIF _OPCION=7 THEN
		SELECT CONTRASENA FROM MAE_CLIENTE WHERE ID_CLIENTE=_ID;
	ELSEIF _OPCION=8 THEN
		SET @SUCURSAL=(SELECT ID_SUCURSAL FROM MAE_CLIENTE WHERE ID_CLIENTE=_ID LIMIT 1);
		SET @NOMBRE_SUCURSAL=(SELECT NOMB_SUCURSAL FROM MAE_SUCURSAL WHERE ID_SUCURSAL=@SUCURSAL LIMIT 1);
		UPDATE MAE_CLIENTE
		SET INTENTO=0,
			SESION='I',
			CONTRASENA =_CONTRASENA
		WHERE ID_CLIENTE=_ID;
		SELECT ID_CLIENTE AS IDCLIENTE,EMAIL, NUMERO_DOCUMENTO FROM MAE_CLIENTE WHERE ID_CLIENTE =_ID;
	ELSEIF _OPCION=9 THEN
			SELECT ID_CLIENTE FROM MAE_CLIENTE WHERE EMAIL =_CLIENTE;
	ELSEIF _OPCION=10 THEN
		SET @IDCLIENTE=(SELECT ID_CLIENTE FROM MAE_CLIENTE WHERE EMAIL =_CLIENTE LIMIT 1);
		UPDATE 	MAE_CLIENTE
		SET INTENTO=0,
			SESION='I',
			CONTRASENA=_CONTRASENA,
			USUARIO_MODIFICA=@IDCLIENTE,
			FECHA_MODIFICA=NOW()
		WHERE ID_CLIENTE=@IDCLIENTE;

		INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
		VALUES (NOW(),@IDCLIENTE,'OLVIDO CONTRASEÑA',_IP,_SERVER);

		SELECT NUMERO_DOCUMENTO,EMAIL FROM MAE_CLIENTE WHERE ID_CLIENTE =@IDCLIENTE;
	ELSEIF _OPCION=11 THEN
		SELECT COUNT(*) as CANTIDAD FROM MAE_CLIENTE
		WHERE EMAIL =_CLIENTE;
	ELSEIF _OPCION=12 THEN
		-- Recuperar contrasena por celular (envio por WhatsApp)
		SET @IDCLIENTE=(SELECT ID_CLIENTE FROM MAE_CLIENTE WHERE NRO_CELULAR =_CLIENTE AND ES_ELIMINADO=0 LIMIT 1);

		IF @IDCLIENTE IS NOT NULL THEN
			UPDATE MAE_CLIENTE
			SET INTENTO=0,
				SESION='I',
				CONTRASENA=_CONTRASENA,
				USUARIO_MODIFICA=@IDCLIENTE,
				FECHA_MODIFICA=NOW()
			WHERE ID_CLIENTE=@IDCLIENTE;

			INSERT INTO SEG_CLIENTE_LOG (FECHA_CLLO,ID_CLIENTE,ESTADO_CLLO,IP_CLLO,SERVIDOR_CLLO)
			VALUES (NOW(),@IDCLIENTE,'OLVIDO CONTRASEÑA (WHATSAPP)',_IP,_SERVER);
		END IF;

		SELECT MC.NUMERO_DOCUMENTO, MC.NRO_CELULAR, MC.EMAIL, MS.NRO_WHATSAPP
		FROM MAE_CLIENTE MC
		INNER JOIN MAE_SUCURSAL MS ON MC.ID_SUCURSAL=MS.ID_SUCURSAL
		WHERE MC.ID_CLIENTE=@IDCLIENTE LIMIT 1;
	ELSEIF _OPCION=13 THEN
		-- Verifica que el celular exista (pre-recuperacion)
		SELECT ID_CLIENTE FROM MAE_CLIENTE WHERE NRO_CELULAR =_CLIENTE AND ES_ELIMINADO=0;
	END IF;
COMMIT;
END$$
DELIMITER ;
