*************************** 1. row ***************************
USP_UPD_INS_CLIENTE
IGNORE_SPACE,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
CREATE DEFINER=`root`@`localhost` PROCEDURE `USP_UPD_INS_CLIENTE`(IN _ID INT,IN _NOMBRES varchar(100), IN _APELLIDO_PATERNO varchar(50),
IN _APELLIDO_MATERNO varchar(50),IN _ID_TIPO_DOCUMENTO int,IN _VIP int,IN _NUMERO_DOCUMENTO varchar(12),IN _DIRECCION varchar(200),IN _FECHA_NACIMIENTO DATETIME,
IN _NRO_CELULAR varchar(9),IN _EMAIL varchar(100),IN _CONTRASENA VARCHAR(255),IN _COMENTARIO varchar(255),IN _IMAGEN varchar(100),IN _TIPO VARCHAR(10), IN _USUACREAMODI INT)
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION, SQLWARNING
BEGIN
ROLLBACK;
SHOW ERRORS LIMIT 1;
RESIGNAL;
END;
DECLARE EXIT HANDLER FOR 1062
BEGIN
	ROLLBACK;
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'El numero de documento ya esta registrado para otro cliente de esta empresa.';
END;
START TRANSACTION;
	SET @SUCURSAL=(SELECT ID_SUCURSAL FROM SEG_USUARIO WHERE ID_USUARIO=_USUACREAMODI LIMIT 1);
	SET @EMPRESA=(SELECT ID_EMPRESA FROM MAE_SUCURSAL WHERE ID_SUCURSAL =@SUCURSAL LIMIT 1);
	SET @NOMBRE_SUCURSAL=(SELECT NOMB_SUCURSAL FROM MAE_SUCURSAL WHERE ID_SUCURSAL=@SUCURSAL LIMIT 1);
	IF _TIPO='edita' THEN
		UPDATE MAE_CLIENTE
		SET NOMBRE=_NOMBRES,
			APELLIDO_PATERNO=_APELLIDO_PATERNO,
			APELLIDO_MATERNO=_APELLIDO_MATERNO,
			NOMBRE=_NOMBRES,
			ID_TIPO_DOCUMENTO=_ID_TIPO_DOCUMENTO,
			VIP=_VIP,
			NUMERO_DOCUMENTO=_NUMERO_DOCUMENTO,
			DIRECCION=_DIRECCION,
			FECHA_NACIMIENTO =_FECHA_NACIMIENTO,
			NRO_CELULAR=_NRO_CELULAR,
			EMAIL=_EMAIL,
			COMENTARIO=_COMENTARIO,
			USUARIO_MODIFICA=_USUACREAMODI,
			FECHA_MODIFICA=NOW()
		WHERE ID_CLIENTE=_ID;

		IF _IMAGEN IS NOT NULL THEN
			UPDATE MAE_CLIENTE
			SET IMAGEN=_IMAGEN
			WHERE ID_CLIENTE=_ID;
		END IF;

		SET @TIPO_DOCUMENTO=(SELECT DESCRIPCION FROM TIPO_PARAMETRO_DETALLE WHERE ID_PARAMETRO_DETALLE=_ID_TIPO_DOCUMENTO);

		SELECT _ID AS ID_CLIENTE, CONCAT(_APELLIDO_PATERNO,' ',_APELLIDO_MATERNO,' ',_NOMBRES) as NOMBRE,_ID_TIPO_DOCUMENTO AS ID_TIPO_DOCUMENTO, @TIPO_DOCUMENTO AS TIPO_DOCUMENTO,
		_NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO, _NRO_CELULAR AS NRO_CELULAR, _EMAIL AS EMAIL, _VIP AS VIP, _IMAGEN AS IMAGEN;
	ELSEIF _TIPO='crea' THEN
		SET @IDSIGUIENTE=(SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='MAE_CLIENTE');
		SET @TIPO_DOCUMENTO=(SELECT DESCRIPCION FROM TIPO_PARAMETRO_DETALLE WHERE ID_PARAMETRO_DETALLE=_ID_TIPO_DOCUMENTO);

		INSERT INTO MAE_CLIENTE
		(ID_SUCURSAL,ID_EMPRESA,NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ,ID_TIPO_DOCUMENTO,VIP,NUMERO_DOCUMENTO,DIRECCION,NRO_CELULAR,EMAIL,CONTRASENA,IMAGEN,COMENTARIO,FECHA_NACIMIENTO,USUARIO_CREA, FECHA_CREA)
		VALUES(@SUCURSAL,@EMPRESA,_NOMBRES, _APELLIDO_PATERNO,_APELLIDO_MATERNO, _ID_TIPO_DOCUMENTO,_VIP, _NUMERO_DOCUMENTO, _DIRECCION, _NRO_CELULAR, _EMAIL,_CONTRASENA,_IMAGEN,_COMENTARIO,_FECHA_NACIMIENTO, _USUACREAMODI, NOW());

		SELECT @IDSIGUIENTE AS ID_CLIENTE,CONCAT(_APELLIDO_PATERNO,' ',_APELLIDO_MATERNO,' ',_NOMBRES) as NOMBRE, _ID_TIPO_DOCUMENTO AS ID_TIPO_DOCUMENTO, @TIPO_DOCUMENTO AS TIPO_DOCUMENTO,
		_NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO, _NRO_CELULAR AS NRO_CELULAR, _EMAIL AS EMAIL, _VIP AS VIP, _IMAGEN AS IMAGEN, @NOMBRE_SUCURSAL AS NOMBRE_SUCURSAL;
	END IF;
COMMIT;
END
utf8mb4
utf8mb4_uca1400_ai_ci
utf8mb4_general_ci
